##Array Inspection:
1.	Write a Python program to create a NumPy array from a list and print its shape.
o	List = [1, 2, 3, 4, 5, 6]


In [5]:
import numpy as np
list = [1, 2, 3, 4, 5, 6]
a= np.array([1, 2, 3, 4, 5, 6])
a.shape
print(a)

[1 2 3 4 5 6]


In [6]:
a.shape

(6,)

2.	Write a Python program to create a NumPy array and print its number of dimensions (ndim).
o	Array = [[1,2,3],[4,5,6]]


In [7]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [8]:
a.ndim

2

3.	Write a Python program to create a NumPy array and print its total number of elements (size).
o	Array = [10, 20, 30, 40, 50]


In [9]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])
print(a)

[10 20 30 40 50]


In [10]:
a.size

5

4.	Write a Python program to find the data type (dtype) of a given NumPy array.
o	Array = [1.0, 2.5, 3.8]


In [11]:
import numpy as np
b = np.array([1.0, 2.5, 3.8])
b.dtype

dtype('float64')

5.	Write a Python program to convert the data type of a NumPy array from float to int using astype().
o	Array = [5.5, 6.7, 8.9]


In [18]:
import numpy as np
a = np.array([5.5, 6.7, 8.9])
b = a.astype('int64')
print(b)

[5 6 8]


#Different Ways of Creating Arrays:

6.	Write a Python program to create a NumPy array initialized with all zeros of size 4.

In [19]:
a = np.zeros((4,4),dtype= int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


7.	Write a Python program to create a NumPy array initialized with all ones of size (2,3).

In [20]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


8.	Write a Python program to create a NumPy array containing numbers from 10 to 30 (excluding 30) using np.arange().

In [21]:
a = np.arange(10,30,1)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


9.	Write a Python program to create a NumPy array of 7 random integers between 0 and 100.

In [28]:
a = np.random.randint(0,100,size=7)
print(a)

[53 11 40 97 79 66 65]


10.	Write a Python program to create an array with 10 numbers evenly spaced between 0 and 5 using linspace().

In [30]:
a = np.linspace(0,5,10)
print(a)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


11.	Write a Python program to create a NumPy array directly from the numbers [11, 22, 33, 44, 55].

In [31]:
a = np.array([11, 22, 33, 44, 55])
print(a)

[11 22 33 44 55]


12.	Write a Python program to create a 1D NumPy array from a given Python list.
o	List = [3, 6, 9, 12, 15]


In [32]:
a = np.array([[3, 6, 9, 12, 15]])
print(a)

[[ 3  6  9 12 15]]


13.	Write a Python program to create a 2D NumPy array from a tuple.
o	Tuple = ((1,2,3),(4,5,6))


In [35]:
Tuple = ((1,2,3),(4,5,6))
arr = np.asarray(Tuple)
print(arr)

[[1 2 3]
 [4 5 6]]


14.	Write a Python program to create a 3x3 identity matrix using NumPy.

In [37]:
matrix = np.identity(3)
print("3x3 Identity Matrix:")
print(matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


15.	Write a Python program to create a 5x5 array initialized with random floats between 0 and 1.

In [41]:
a = np.random.random((5,5))
print(a)

[[0.87942929 0.98605768 0.11253962 0.49857484 0.82621715]
 [0.20470497 0.08251469 0.02389742 0.12737323 0.19614592]
 [0.17128397 0.28369992 0.7774006  0.10268564 0.16051212]
 [0.74119117 0.71353173 0.12003997 0.80580591 0.92226557]
 [0.85372173 0.78836542 0.94441597 0.50045325 0.02712146]]


16.	Write a Python program to create an array of even numbers from 2 to 20 using np.arange().

In [42]:
a = np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


17.	Write a Python program to create an array with random integers between 50 and 100 and print its shape, size, and dtype.
o	(Array should have 2 rows and 5 columns.)


In [50]:
a = np.random.randint(50,100,size= (2,5))
print(a)
a.shape
#a.size
# a.dtype

[[60 98 76 64 99]
 [98 63 98 52 67]]


(2, 5)

In [51]:
a.size

10

In [52]:
a.dtype

dtype('int64')

18.	Write a Python program to create an array from existing data [7, 14, 21, 28, 35] and print its number of dimensions.

In [54]:
a = np.array([7, 14, 21, 28, 35])
print(a)
a.ndim

[ 7 14 21 28 35]


1

19.	Write a Python program to create an array from a list of strings ['apple', 'banana', 'cherry'] and print its data type.

In [56]:
str = np.array(['apple', 'banana', 'cherry'])
print(str)
str.dtype

['apple' 'banana' 'cherry']


dtype('<U6')

20.	Write a Python program to create an array of 10 numbers between 1 and 2 using linspace() and print the array.

In [57]:
a = np.linspace(1,2,10)
print(a)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
