Given a 2D NumPy array arr_2d, transpose the array and print the result.

Example Input:


arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

Example Output:


Transposed Array:
[[1 4]
 [2 5]
 [3 6]]



In [2]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
b = np.transpose(arr_2d)
print(b)

[[1 4]
 [2 5]
 [3 6]]


## Question 2: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 3x2 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6])

Example Output:

Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]


In [6]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
b = np.reshape(arr_1d, (3,2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


## Question 3: Resize Array
Given a 1D NumPy array arr_1d, resize it into a 3x3 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
Example Output:


Resized Array:
[[1 2 3]
 [4 5 6]
 [7 8 1]]


In [7]:
 a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
 b = np.resize(a, (3,3))
 print(b)

[[1 2 3]
 [4 5 6]
 [7 8 1]]


## Question 4: Flatten Array
Given a 2D NumPy array arr_2d, flatten it and print the result.

Example Input:

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
Example Output:


Flattened Array:
[1 2 3 4 5 6]


In [9]:
a= np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten()
print(b)

[1 2 3 4 5 6]


## Question 5: Transpose Array
Given a 3D NumPy array arr_3d, transpose the array and print the result.

Example Input:

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

Example Output:


Transposed Array:
[[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]]



In [10]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
b = np.transpose(a)
print(b)



[[[ 1  5  9]
  [ 3  7 11]]

 [[ 2  6 10]
  [ 4  8 12]]]


## Question 6: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 4x3 array and print the result.

Example Input:


arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

Example Output:

Reshaped Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



In [13]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = np.reshape(a, (4,3))
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Question 7: Resize Array
Given a 2D NumPy array arr_2d, resize it into a 4x4 array and print the result.

Example Input:


arr_2d = np.array([[1, 2], [3, 4]])

Example Output:

Resized Array:
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


In [20]:
a = np.array([[1, 2], [3, 4]])
b = np.resize(a, (4, 4))
print("Resized Array:", b)

Resized Array: [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


## Question 8: Flatten Array
Given a 3D NumPy array arr_3d, flatten it and print the result.

Example Input:



arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

Example Output:


Flattened Array:
[1 2 3 4 5 6 7 8]


In [21]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b = a.flatten()
print(b)

[1 2 3 4 5 6 7 8]


Question 1: Given a 1D NumPy array arr_1d, extract and print the first element.



arr_1d = np.array([1, 2, 3, 4, 5])


In [31]:
arr_1d = np.array([1, 2, 3, 4, 5])
b= arr_1d[0]
print(b)

1


Question 2: Given a 1D NumPy array arr_1d, extract and print the last three elements.




arr_1d = np.array([1, 2, 3, 4, 5])

In [34]:
arr_1d = np.array([1, 2, 3, 4, 5])
b = arr_1d[2:]
print(b)

[3 4 5]


Question 3: Given a 2D NumPy array arr_2d, extract and print the element at the second row and third column.



arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [36]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = arr_2d[1,2]
print(b)

6


Question 4: Given a 2D NumPy array arr_2d, extract and print the first row.



arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])



In [38]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = arr_2d[0]
print(b)

[1 2 3]


Question 5: Given a 2D NumPy array arr_2d, extract and print the last column.



arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])



In [43]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = arr_2d[:,-1]
print(b)

[3 6 9]


Question 6: Given a 3D NumPy array arr_3d, extract and print the element at the second matrix, third row, and third column.


arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])


In [47]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
b = arr_3d[1,2,2]
print(b)

18


Question 7: Given a 3D NumPy array arr_3d, extract and print the first matrix.


arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])


In [50]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
b=  arr_3d[0]
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Question 8: Given a 3D NumPy array arr_3d, extract and print the last matrix.


arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])


In [51]:
 arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
 b = arr_3d[1]
 print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]
